version: '2'

volumes:
  pgdata:
  redisdata:

services:
  web:
      build: .
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
          - .:/code
      ports:
          - "8000:8000"
      env_file: .env
      entrypoint: ./.wait-for-pg.sh postgres
      depends_on:
        - postgres
        - redis

  postgres:
      restart: always
      image: postgres:latest
      ports:
         - "5432"
      volumes:
        - pgdata:/var/lib/postgresql/data/

  redis:
      restart: always
      image: redis:latest
      ports:
        - "6379"
      volumes:
        - redisdata:/data


